CREATE TABLE cron(
id INT generated by default as identity PRIMARY KEY /* auto increment */,
baby_id VARCHAR(32),
time INT,
status SMALLINT,
application_name VARCHAR(100),
application_id INT,
baby_birth_week SMALLINT,
timeh TIMESTAMP(0),
doctor_id INT,  
FOREIGN KEY(doctor_id) 
    REFERENCES doctors(doctor_id)
FOREIGN KEY(baby_id) 
    REFERENCES baby_table(baby_id)    
FOREIGN KEY(application_id) 
    REFERENCES application_list(id)                
)