create table cron
(
    id               integer generated by default as identity,
    baby_id          varchar(32),
    time             integer,
    status           smallint,
    application_name varchar(100),
    application_id   integer,
    timeh            timestamp(0),
    doctor_id        integer
);